
export function fetchProducts() {
  return Promise.resolve({data: [
    {regex: '(ABOBORA)', text: 'Abóbora'},
    {regex: '(INTIMUS|ABSORVENTE)', text: 'Absorvente'},
    {regex: '(ACEM)', text: 'Acem'},
    {regex: '(ACUCAR|AC DEMERARA)', text: 'Açúcar'},
    {regex: '(AGUA |AG M)', text: 'Água 1.5L'},
    {regex: '(ALHO)', text: 'Alho'},
    {regex: '(AMAC)', text: 'Amaciante'},
    {regex: '(ARROZ)', text: 'Arroz'},
    {regex: '(ATUM)', text: 'Atum'},
    {regex: '(AVEIA)', text: 'Aveia'},
    {regex: '(AZEITE)', text: 'Azeite'},
    {regex: '(BACON|BAC PALETA)', text: 'Bacon'},
    {regex: '(BANANA)', text: 'Banana'},
    {regex: '(BATATA)', text: 'Batata'},
    {regex: '(BERINJ)', text: 'Berinjela'},
    {regex: '(BILL|JACK)', text: 'Billy&Jack'},
    {regex: '(BISC)', text: 'Biscoito'},
    {regex: '(C 3 CORACOES|CAFE)', text: 'Café'},
    {regex: '(CAMARAO)', text: 'Camarão'},
    {regex: '(CEBOLA)', text: 'Cebola'},
    {regex: '(CEBOLINHA)', text: 'Cebolinha'},
    {regex: '(CARNE BOV PALETA|CARNE MOIDA|PATINHO|PEITO BOV)', text: 'Carne Moída'},
    {regex: '(CERV|CER HEINEKEN)', text: 'Cerveja'},
    {regex: '(CHA )', text: 'Chá'},
    {regex: '(COUVE)', text: 'Couve'},
    {regex: '(COGUMELO|COG )', text: 'Cogumelo'},
    {regex: '(COUVE)', text: 'Couve'},
    {regex: '(CREAM CHEESE|CR CHEESE)', text: 'Cream Cheese'},
    {regex: '(CREME LEITE|CR LEITE)', text: 'Creme de Leite'},
    {regex: '(DETERG)', text: 'Detergente'},
    {regex: '(DESOD)', text: 'Desodorante'},
    {regex: '(TININDO|ESPONJA)', text: 'Esponja'},
    {regex: '(FARINHA)', text: 'Farinha'},
    {regex: '(FEIJAO)', text: 'Feijão'},
    {regex: '(FRALDINH)', text: 'Fraldinha'},
    {regex: '(GRANOLA)', text: 'Granola'},
    {regex: '(KETCHUP)', text: 'Ketchup'},
    {regex: '(KOMBUCHA)', text: 'Kombucha'},
    {regex: '(NOT MILK|NOTMIL)', text: 'Leite'},
    {regex: '(LIMAO)', text: 'Limão Taiti'},
    {regex: '(LIN CAL)', text: 'Linguiça Calabresa'},
    {regex: '(MACARRAO|MAC D BENTA|MASSA ALIM ARROZ|MASSA ALIM.URBANO|MASSA ARROZ)', text: 'Macarrão'},
    {regex: '(MAIONESE)', text: 'Maionese'},
    {regex: '(MAMAO)', text: 'Mamão Papaya'},
    {regex: '(MANT)', text: 'Manteiga'},
    {regex: '(MARACUJA)', text: 'Maracujá'},
    {regex: '(MARG)', text: 'Margarina'},
    {regex: '(MORANGO)', text: 'Morango'},
    {regex: '(MOST)', text: 'Mostarda'},
    {regex: '(EMPAN|GGETS|TEK)', text: 'Nuggets'},
    {regex: '(OVOS|OV |OVO )', text: 'Ovos'},
    {regex: '(OLEO)', text: 'Óleo'},
    {regex: '(QJ|QUEIJO)', text: 'Queijo'},
    {regex: '(PAO HAMBURG|PAO PULLM)', text: 'Pão de Hamburguer'},
    {regex: '(PATINHO)', text: 'Patinho'},
    {regex: '(PEITO BOV)', text: 'Peito Bovino'},
    {regex: '(HIG)', text: 'Papel Higiênico'},
    {regex: '(TOALHA|T PAPEL)', text: 'Papel Toalha'},
    {regex: '(CREME DENT|CREME COLGATE|CREM COLGATE|CRM DENT|GEL DENT)', text: 'Pasta de Dentes'},
    {regex: '(PEITO FGO|FILE SADIA)', text: 'Peito de Frango'},
    {regex: '(RAP ?10)', text: 'Rap 10'},
    {regex: '(REQUEIJAO|REQ)', text: 'Requeijão'},
    {regex: '(LAVA R)', text: 'Sabão em Pó'},
    {regex: '(SAB |SABON)', text: 'Sabonete'},
    {regex: '(SALMAO)', text: 'Salmão'},
    {regex: '(SARD)', text: 'Sardinha'},
    {regex: '(SHOYU)', text: 'Shoyu'},
    {regex: '(COXA |SOBRECO)', text: 'Sobrecoxa/Coxa de Frango'},
    {regex: '(SUCO)', text: 'Suco'},
    {regex: '(TAP|TERRINHA|GOMA)', text: 'Tapioca'},
    {regex: '(TILAPIA)', text: 'Tilápia'},
    {regex: '(TOMATE PELADO)', text: 'Tomate Pelado'},
    {regex: '(GRAPE)', text: 'Tomatinho'},
    {regex: '(VINHO |VIN |V AFR|V ARG|V ESP|V NAC|V CH|VHO)', text: 'Vinho'},
  ]});
}
